apiVersion: apps/v1
kind: Deployment
metadata:
  name: caiocunha-playlist-recommender-deploy
  namespace: caiocunha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caiocunha-playlist-recommender
  template:
    metadata:
      labels:
        app: caiocunha-playlist-recommender
    spec:
      containers:
      - name: caiocunha-playlist-recommender-server
        image: caiotcunha/playlist-recomender-server:0.2
        imagePullPolicy: Always
        env:
          - name: MODELPATH
            value: /data/model.pickle
          - name: APP_VERSION
            value: "1.0.1"
        ports:
        - containerPort: 50033
        volumeMounts:
        - mountPath: /data
          name: persistent-storage
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: project2-pv-caiocunha